vich_uploader:
    db_driver: orm

    mappings:
       recipe_images:
           uri_prefix: /images/recette
           upload_destination: '%kernel.project_dir%/public/images/recette'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
